/**
 * POST /api/business/passkeys/register/start
 *
 * Step 1 of WebAuthn passkey registration.
 *
 * Generates registration options for the authenticator and stores the
 * challenge in Supabase (passkey_challenges) with a 5-minute expiry.
 *
 * Request body: { userId: string, userName: string, displayName?: string }
 * Response:     PublicKeyCredentialCreationOptionsJSON (feed directly to
 *               @simplewebauthn/browser startRegistration())
 *
 * The challenge is a cryptographically random base64url string generated by
 * @simplewebauthn/server.  It is tied to the userId and expires in 5 minutes
 * to prevent replay attacks.
 */

import type { APIRoute } from 'astro';
import { generateRegistrationOptions } from '@simplewebauthn/server';
import { getSupabase } from '../../../../../lib/supabase';
import { json, err } from '../../../../../lib/api-helpers';

export const prerender = false;

const RP_ID   = () => import.meta.env.WEBAUTHN_RP_ID   || 'localhost';
const RP_NAME = () => import.meta.env.WEBAUTHN_RP_NAME || 'ServiceSurfer Business';

export const POST: APIRoute = async ({ request }) => {
  const body = await request.json().catch(() => null);
  if (!body?.userId || !body?.userName) {
    return err('userId and userName required', 400);
  }

  const userId      = String(body.userId).slice(0, 64);
  const userName    = String(body.userName).slice(0, 120);
  const displayName = body.displayName ? String(body.displayName).slice(0, 120) : userName;

  const sb = getSupabase();
  if (!sb) return err('database unavailable', 503);

  // Fetch existing credentials to populate excludeCredentials (prevents re-registration)
  const existingResult = await sb
    .from('user_passkeys')
    .select('credential_id, transports')
    .eq('user_id', userId)
    .then(r => r, () => ({ data: null })) as { data: Array<{ credential_id: string; transports: string[] }> | null };

  const excludeCredentials = (existingResult.data ?? []).map(k => ({
    id:         k.credential_id,
    transports: (k.transports ?? []) as AuthenticatorTransport[],
  }));

  // Generate registration options
  const options = await generateRegistrationOptions({
    rpName:                 RP_NAME(),
    rpID:                   RP_ID(),
    userID:                 new TextEncoder().encode(userId),
    userName,
    userDisplayName:        displayName,
    attestationType:        'none',
    authenticatorSelection: {
      residentKey:        'preferred',
      userVerification:   'preferred',
      authenticatorAttachment: 'platform',
    },
    excludeCredentials,
    timeout: 300_000, // 5 minutes
  });

  // Persist challenge in Supabase — expires in 5 minutes
  const expiresAt = new Date(Date.now() + 5 * 60 * 1000).toISOString();
  const { error: dbError } = await sb.from('passkey_challenges').insert({
    user_id:    userId,
    purpose:    'register',
    challenge:  options.challenge,
    expires_at: expiresAt,
    used_at:    null,
  } as never);

  if (dbError) {
    console.error('[passkeys/register/start] DB error:', dbError.message);
    return err('failed to store challenge', 500);
  }

  return json(options);
};

